
/*copyright 2010 Simon Graeser*/

/*
This file is part of Pina.

Pina is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Pina is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with Pina.  If not, see <http://www.gnu.org/licenses/>.
*/

#include "Element.h"

#include "Core/Accessor.h"
#include "Core/Altitude.h"
#include "Core/Ambient.h"
#include "Core/Animation.h"
#include "Core/AnimationClip.h"
#include "Core/Aspect_ratio.h"
#include "Core/Asset.h"
#include "Core/Author.h"
#include "Core/Author_email.h"
#include "Core/Author_website.h"
#include "Core/Authoring_tool.h"
#include "Core/Bind_shape_matrix.h"
#include "Core/Bool_array.h"
#include "Core/Camera.h"
#include "Core/Channel.h"
#include "Core/Collada.h"
#include "Core/Color.h"
#include "Core/Comments.h"
#include "Core/Constant_attenuation.h"
#include "Core/Contributor.h"
#include "Core/Control_vertices.h"
#include "Core/Controller.h"
#include "Core/Copyright.h"
#include "Core/Coverage.h"
#include "Core/Created.h"
#include "Core/Directional.h"
#include "Core/Evaluate_scene.h"
#include "Core/Extra.h"
#include "Core/Falloff_angle.h"
#include "Core/Falloff_exponent.h"
#include "Core/Float_array.h"
#include "Core/Formula.h"
#include "Core/Geographic_location.h"
#include "Core/Geometry.h"
#include "Core/H.h"
#include "Core/IDREF_array.h"
#include "Core/Imager.h"
#include "Core/Input_shared.h"
#include "Core/Input_unshared.h"
#include "Core/Instance_animation.h"
#include "Core/Instance_camera.h"
#include "Core/Instance_controller.h"
#include "Core/Instance_formula.h"
#include "Core/Instance_geometry.h"
#include "Core/Instance_light.h"
#include "Core/Instance_node.h"
#include "Core/Instance_visual_scene.h"
#include "Core/Int_array.h"
#include "Core/Joints.h"
#include "Core/Keywords.h"
#include "Core/Latitude.h"
#include "Core/Library_animation_clips.h"
#include "Core/Library_animations.h"
#include "Core/Library_cameras.h"
#include "Core/Library_controllers.h"
#include "Core/Library_formulas.h"
#include "Core/Library_geometries.h"
#include "Core/Library_lights.h"
#include "Core/Library_nodes.h"
#include "Core/Library_visual_scenes.h"
#include "Core/Light.h"
#include "Core/Linear_attenuation.h"
#include "Core/Lines.h"
#include "Core/Linestrips.h"
#include "Core/Longitude.h"
#include "Core/Lookat.h"
#include "Core/Matrix.h"
#include "Core/Mesh.h"
#include "Core/Modified.h"
#include "Core/Morph.h"
#include "Core/Name_array.h"
#include "Core/Newparam.h"
#include "Core/Node.h"
#include "Core/Optics.h"
#include "Core/Orthographic.h"
#include "Core/P.h"
#include "Core/Param_data_flow.h"
#include "Core/Param_reference.h"
#include "Core/Perspective.h"
#include "Core/Ph.h"
#include "Core/Point.h"
#include "Core/Polygons.h"
#include "Core/Polylist.h"
#include "Core/Quadratic_attenuation.h"
#include "Core/Revision.h"
#include "Core/Rotate.h"
#include "Core/SIDREF_array.h"
#include "Core/Sampler.h"
#include "Core/Scale.h"
#include "Core/Scene.h"
#include "Core/Setparam.h"
#include "Core/Skeleton.h"
#include "Core/Skew.h"
#include "Core/Skin.h"
#include "Core/Source.h"
#include "Core/Source_data.h"
#include "Core/Spline.h"
#include "Core/Spot.h"
#include "Core/Subject.h"
#include "Core/Target.h"
#include "Core/Targets.h"
#include "Core/Technique.h"
#include "Core/Technique_common.h"
#include "Core/Title.h"
#include "Core/Token_array.h"
#include "Core/Translate.h"
#include "Core/Triangles.h"
#include "Core/Trifans.h"
#include "Core/Tristrips.h"
#include "Core/Unit.h"
#include "Core/Unkown.h"
#include "Core/Up_axis.h"
#include "Core/V.h"
#include "Core/Vcount.h"
#include "Core/Vertex_weights.h"
#include "Core/Vertices.h"
#include "Core/Visual_scene.h"
#include "Core/Xfov.h"
#include "Core/Xmag.h"
#include "Core/Yfov.h"
#include "Core/Ymag.h"
#include "Core/Zfar.h"
#include "Core/Znear.h"


